language: node_js
node_js:
  - 0.8
branches:
  only:
    - travis
    - active
    - master
notifications:
  email:
    recipients:
      - admin@astrolet.net
    on_success: change
    on_failure: always

